name: List Public Likelihoods

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  # Run daily at 0:01 UTC
  schedule:
    - cron:  '1 0 * * *'

jobs:
  list_likelihoods:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kind:
          - atlas
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r ${{ matrix.kind }}/requirements.txt

      - name: Generate list of likelihoods
        run: python ${{ matrix.kind }}/main.py > ${{ matrix.kind }}.json

      - name: Check valid JSON
        run: jq -reM '""' ${{ matrix.kind }}.json

      - name: Upload generated list
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.kind }}
          path: ${{ matrix.kind }}.json

  prepare_website:
    runs-on: ubuntu-latest
    needs: list_likelihoods
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v1

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts/

      - name: List artifacts
        run: ls -R
        working-directory: artifacts

      - name: Move to deploy directory
        run: |
          find artifacts -name "*.json" -print0 | xargs -0 -I file mv "file" deploy/

      - name: List contents
        run: ls -R
        working-directory: deploy

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: deploy/

  deploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: prepare_website
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
